# HTTP Server
server:
  port: 15681  # HTTP (Tomcat) port

spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ts-ticketinfo-service


swagger:
  controllerPackage: ticketinfo.controller