spring:
  application:
    name: ts-consign-price-service
  data:
    mongodb:
      host: ts-consign-price-mongo
      database: ts
      port: 27017


# HTTP Server
mvf4ms:
  version: 1.0.0
server:
  port: 16110

swagger:
  controllerPackage: consignprice.controller