#spring:
#  data:
#    mongodb:
#      host: ts-preserve-other-mongo
##      username: user
##      password: ${MONGODB_PASSWORD}
##      database: piggymetrics
#      port: 27017

# HTTP Server
mvf4ms:
  version: 1.0.0
server:
  port: 14569 # HTTP (Tomcat) port

spring:
  application:
    name: ts-preserve-other-service

swagger:
  controllerPackage: preserveOther.controller
