# HTTP Server
server:
  port: 12031  # HTTP (Tomcat) port

mvf4ms:
  version: 1.0.0
spring:
  application:
    name: ts-order-service
  data:
    mongodb:
      host: ts-order-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

swagger:
  controllerPackage: order.controller