spring:
  application:
    name: ts-config-service
  data:
    mongodb:
      host: ts-config-mongo
      #       username: user
      #       password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

# HTTP Server
mvf4ms:
  version: 1.0.0
server:
  port: 15679  # HTTP (Tomcat) port

swagger:
  controllerPackage: config.controller
