version: '2'

services:
  ts-user-service:
    image: codewisdom/ts-user-service-with-jaeger:v1
    restart: always
    ports:
      - 12342:12342
    networks:
      - my-network

  ts-user-mongo:
    image: mongo
    networks:
      - my-network

  ts-auth-service:
    image: codewisdom/ts-auth-service-with-jaeger:v1
    restart: always
    ports:
      - 12340:12340
    networks:
      - my-network

  ts-auth-mongo:
    image: mongo
    networks:
      - my-network

  ts-verification-code-service:
    image: codewisdom/ts-verification-code-service-with-jaeger:v1
    restart: always
    ports:
      - 15678:15678
    networks:
      - my-network

  ts-admin-user-service:
    image: codewisdom/ts-admin-user-service-with-jaeger:v1
    restart: always
    ports:
      - 16115:16115
#    deploy:
#      replicas: 1
#      restart_policy:
#        condition: on-failure
    networks:
      - my-network

  ts-station-service:
    image: codewisdom/ts-station-service-with-jaeger:v1
    restart: always
    ports:
      - "12345"
    networks:
      - my-network

  ts-station-mongo:
    image: mongo
    networks:
      - my-network

  ts-basic-service:
    image: codewisdom/ts-basic-service-with-jaeger:v1
    restart: always
    ports:
      - "15680"
    networks:
      - my-network

  ts-ticketinfo-service:
    image: codewisdom/ts-ticketinfo-service-with-jaeger:v1
    restart: always
    ports:
      - "15681:15681"
    networks:
      - my-network

  jaeger:
    image: jaegertracing/all-in-one:1.15
    ports:
      - "16686:16686"
#    deploy:
#      replicas: 1
#      restart_policy:
#        condition: on-failure
    networks:
      - my-network

networks:
  my-network:
    driver: bridge