version: '2'

services:

  zipkin:
    image: my_zipkin
    ports:
      - "9411:9411"
#    environment:
#      MYSQL_USER: root
#      MYSQL_PASS: 123456
#      MYSQL_HOST: 60.205.188.102
#      STORAGE_TYPE: mysql
#      MYSQL_DB: zipkin
#      MYSQL_TCP_PORT: 3306
    networks:
      - my-network
#    depends_on:
#      - ts-mysql
#
#  ts-mysql:
#    image: mysql
#    expose:
#      - "3306"
#    ports:
#      - "3308:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#    networks:
#      - my-network

  ts-station-service:
    build: ../ts-station-service
    restart: always
    ports:
      - 12345:12345
    networks:
      - my-network

  ts-station-mongo:
    image: mongo
    networks:
      - my-network


  ts-basic-service:
    build: ../ts-basic-service
    restart: always
    ports:
      - 15680:15680
    networks:
      - my-network

  ts-ticketinfo-service:
    build: ../ts-ticketinfo-service
    restart: always
    ports:
      - 15681:15681
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
#    external: true