server:
  port: 18898

spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ts-seat-service

swagger:
  controllerPackage: seat.controller