server:
  port: 12386

spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ts-execute-service
swagger:
  controllerPackage: execute.controller