server:
  port: 15678  # HTTP (Tomcat) port

spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ts-verification-code-service

swagger:
  controllerPackage: verifycode.controller