server:
  port: 18767

spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ts-admin-basic-info-service

swagger:
  controllerPackage: adminbasic.microservice