server:
  port: 16112

spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ts-admin-order-service


swagger:
  controllerPackage: adminorder.controller