# HTTP Server
server:
  port: 14322  # HTTP (Tomcat) port

spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ts-travel-plan-service


swagger:
  controllerPackage: travelplan.controller