server:
  port: 18885  # HTTP (Tomcat) port

spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ts-cancel-service

swagger:
  controllerPackage: cancel.controller