server:
  port: 16113

spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ts-admin-route-service

swagger:
  controllerPackage: adminroute.controller