server:
  port: 16115

spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ts-admin-user-service

swagger:
  controllerPackage: adminuser.controller