server:
  port: 15680

spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ts-basic-service

swagger:
  controllerPackage: fdse.microservice.controller