server:
  port: 16114

spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: ts-admin-travel-service

swagger:
  controllerPackage: admintravel.controller