apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-station-service
spec:
  selector:
    matchLabels:
      app: ts-station-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-station-service
    spec:
      containers:
        - name: ts-station-service
          image: codewisdom/ts-station-service:0.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 12345
          resources:
            requests:
              cpu: 50m
              memory: 160Mi
            limits:
              cpu: 200m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 12345
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-basic-service
spec:
  selector:
    matchLabels:
      app: ts-basic-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-basic-service
    spec:
      containers:
        - name: ts-basic-service
          image: codewisdom/ts-basic-service:0.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 15680
          resources:
            requests:
              cpu: 50m
              memory: 160Mi
            limits:
              cpu: 200m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 15680
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-ticketinfo-service
spec:
  selector:
    matchLabels:
      app: ts-ticketinfo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-ticketinfo-service
    spec:
      containers:
        - name: ts-ticketinfo-service
          image: codewisdom/ts-ticketinfo-service:0.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 15681
          resources:
            requests:
              cpu: 50m
              memory: 160Mi
            limits:
              cpu: 200m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 15681
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ts-station-service
spec:
  ports:
    - name: http
      port: 12345
  selector:
    app: ts-station-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-ticketinfo-service
spec:
  ports:
    - name: http
      port: 15681
  selector:
    app: ts-ticketinfo-service
---

apiVersion: v1
kind: Service
metadata:
  name: ts-basic-service
spec:
  ports:
    - name: http
      port: 15680
  selector:
    app: ts-basic-service

---