version: '2'

services:
  ts-a-datainit:
    build: ../ts-a-datainit
    restart: always
    ports:
      - 18000:18000
    networks:
      - my-network

  ts-inside-payment-service:
    build: ../ts-inside-payment-service
    restart: always
    ports:
      - 18673:18673
    networks:
      - my-network

  ts-inside-payment-mongo:
    image: mongo
    networks:
      - my-network

  ts-contacts-service:
    build: ../ts-contacts-service
    restart: always
    ports:
      - "12347:12347"
    networks:
      - my-network

  ts-contacts-mongo:
    image: mongo
    networks:
      - my-network


  ts-user-service:
    build: ../ts-user-service
    restart: always
    ports:
      - "12342:12342"
    networks:
      - my-network

  ts-user-mongo:
    image: mongo
    networks:
      - my-network

  ts-auth-service:
    build: ../ts-auth-service
    restart: always
    ports:
      - "12340:12340"
    networks:
      - my-network

  ts-auth-mongo:
    image: mongo
    networks:
      - my-network

  ts-verification-code-service:
    build: ../ts-verification-code-service
    restart: always
    ports:
      - "15678:15678"
    networks:
      - my-network

  ts-admin-user-service:
    build: ../ts-admin-user-service
    restart: always
    ports:
      - "16115:16115"
    #    deploy:
    #      replicas: 1
    #      restart_policy:
    #        condition: on-failure
    networks:
      - my-network

  ts-admin-basic-info-service:
    build: ../ts-admin-basic-info-service
    #image: codewisdom/ts-admin-basic-info-service
    restart: always
    ports:
      - 18767:18767
    networks:
      - my-network


  ts-payment-service:
    build: ../ts-payment-service
    restart: always
    ports:
      - 19001:19001
    networks:
      - my-network

  ts-payment-mongo:
    image: mongo
    networks:
      - my-network

networks:
  my-network:
    driver: bridge