mvf4ms:
  version: 1.0.0
spring:
  application:
    name: ts-consign-service
  data:
    mongodb:
      host: ts-consign-mongo
      database: ts
      port: 27017


# HTTP Server
server:
  port: 16111

swagger:
  controllerPackage: consign.controller